version: '3'
services:
  web:
    build: .
    expose:
      - "5000"
    deploy:
      replicas: 3 # Запускаем 3 экземпляра Flask-приложения
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: flask_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5