name: Deploy to Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        run: |
          ssh -i $SSH_PRIVATE_KEY -p 22 user@91.184.240.238 "docker pull m1estere/flask-app:latest && docker-compose up -d"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

#91.184.240.238 22